name: database

on:
  schedule:
    # Every day at 4:03 UTC: https://crontab.guru/#3_4_*_*_*
    - cron: "3 4 * * *"

jobs:
  maintenance:
    # TODO(dotdoom): infer project name from repository.
    if: startsWith(github.repository, 'dasfoo/')
    env:
      PROJECT: delern-e1b33
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
        working-directory: firebase
      - run: >
          gcloud auth activate-service-account --key-file <(
            base64 -d <<<'${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}'
          )
      - run: >
          curl
          --max-time 300
          https://us-central1-${PROJECT}.cloudfunctions.net/databaseMaintenance
          -H "Authorization: bearer $(gcloud auth print-identity-token)"
